# Generated by Django 5.0.7 on 2024-07-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('i', 'First Yesr'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], default=1, max_length=1)),
                ('book', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('BookNumber', models.IntegerField()),
                ('Issued_date', models.DateField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
